# NOTE - you also need to install my version of pycocotools:
# https://github.com/jayelm/cocoapi
name: compexp
channels:
  - conda-forge
dependencies:
  # I haven't specified pytorch here
  - python=3.7
  - pandas
  - tqdm
  - imageio
  - scipy
  - matplotlib
  - Pillow
  - seaborn
  - scikit-image
  - pyparsing==2.2.1
  - nltk
  - pip
  - scikit-learn
  - cython==3.0
  - pip:
    - pyeda
    - benepar
  - spacy==2.2.4
